# Generated by Django 3.1.3 on 2020-11-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0005_auto_20201123_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comments',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
