# Generated by Django 3.1.3 on 2020-11-23 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0006_image_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
